project_name: dl-talebook

before:
  hooks:
    - go mod tidy

builds:
  - id: dl-talebook
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^web:'

archives:
  - id: dl-talebook
    builds:
      - dl-talebook
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ incpatch .Version }}-next"
